config/routes.rb
Rails.application.routes.draw do
  resources :notices
  resources :usergroups
  resources :categories
  devise_for :users

  root 'notices#index'

  post 'notice/access/:id' => 'notices#grant_access', as: :grant_notice_access
  delete 'notice/access/:id/:usergroup_id' => 'notices#revoke_access', as: :revoke_notice_access

  post 'usergroup/user/:id' => 'usergroups#add_user', as: :add_user_to_group
  delete 'usergroup/user/:id/:user_id' => 'usergroups#remove_user', as: :remove_user_from_group

end

app/models/usergroup.rb
class Usergroup < ActiveRecord::Base
  belongs_to :admin, :class_name => "User"
  has_and_belongs_to_many :notices
  has_and_belongs_to_many :users

  validates_presence_of :admin
  validates_presence_of :name

  scope :own, lambda { |user|
              where("admin_id = ?", user.id)
            }
end

app/controllers/usergroups_controller.rb
class UsergroupsController < ApplicationController
  before_action :set_usergroup, only: [:show, :edit, :update, :destroy, :add_user, :remove_user]
  before_action :set_user, only: [:add_user, :remove_user]

  # GET /usergroups
  # GET /usergroups.json
  def index
    @usergroups = Usergroup.all
  end

  # GET /usergroups/1
  # GET /usergroups/1.json
  def show
    if @usergroup.admin == current_user

    else
      respond_to do |format|
        format.html { redirect_to usergroups_url, alert: 'You have no right to view this usergroup.' }
        format.json { head :no_content }
      end
    end
  end

  # GET /usergroups/new
  def new
    @usergroup = Usergroup.new
  end

  # GET /usergroups/1/edit
  def edit
    if @usergroup.admin == current_user

    else
      respond_to do |format|
        format.html { redirect_to usergroups_url, alert: 'You have no right to edit this usergroup.' }
        format.json { head :no_content }
      end
    end
  end

  # POST /usergroups
  # POST /usergroups.json
  def create
    @usergroup = Usergroup.new(usergroup_params)
    @usergroup.admin = current_user

    respond_to do |format|
      if @usergroup.save
        format.html { redirect_to @usergroup, notice: 'Usergroup was successfully created.' }
        format.json { render :show, status: :created, location: @usergroup }
      else
        format.html { render :new }
        format.json { render json: @usergroup.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /usergroups/1
  # PATCH/PUT /usergroups/1.json
  def update
    if @usergroup.admin == current_user
      respond_to do |format|
        if @usergroup.update(usergroup_params)
          format.html { redirect_to @usergroup, notice: 'Usergroup was successfully updated.' }
          format.json { render :show, status: :ok, location: @usergroup }
        else
          format.html { render :edit }
          format.json { render json: @usergroup.errors, status: :unprocessable_entity }
        end
      end
    else
      respond_to do |format|
        format.html { redirect_to usergroups_url, alert: 'You have no right to update this usergroup.' }
        format.json { head :no_content }
      end
    end
  end

  # DELETE /usergroups/1
  # DELETE /usergroups/1.json
  def destroy
    if @usergroup.admin == current_user
      @usergroup.destroy
      respond_to do |format|
        format.html { redirect_to usergroups_url, notice: 'Usergroup was successfully deleted.' }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html { redirect_to usergroups_url, alert: 'You have no right to delete this usergroup.' }
        format.json { head :no_content }
      end
    end
  end

  def add_user
    if @usergroup.admin == current_user
      unless @user.nil? || @user == current_user
        begin
          @usergroup.users.find(@user)
        rescue ActiveRecord::RecordNotFound
          @usergroup.users << @user
        end

        respond_to do |format|
          format.html { redirect_to @usergroup, notice: 'User added.' }
          format.json { head :no_content }
        end
      else
        respond_to do |format|
          format.html { redirect_to @usergroup, notice: 'Not possible to add user.' }
          format.json { head :no_content }
        end
      end
    else
      respond_to do |format|
        format.html { redirect_to @usergroup, alert: 'You have no right to add users.' }
        format.json { head :no_content }
      end
    end
  end

  def remove_user
    if @usergroup.admin == current_user
      unless @user.nil? || @user == current_user
        @usergroup.users.delete(@user)

        respond_to do |format|
          format.html { redirect_to @usergroup, notice: 'User removed.' }
          format.json { head :no_content }
        end
      else
        respond_to do |format|
          format.html { redirect_to @usergroup, notice: 'Not possible to remove user.' }
          format.json { head :no_content }
        end
      end
    else
      respond_to do |format|
        format.html { redirect_to @usergroup, alert: 'You have no right to remove users.' }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_usergroup
      @usergroup = Usergroup.find(params[:id])
    end

    def set_user
      @user = User.where(id: params[:user_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def usergroup_params
      params.require(:usergroup).permit(:name)
    end
end

app/helpers/usergroups_helper.rb
module UsergroupsHelper
end

app/views/usergroups/_form.html.slim
- readonly ||= false

= form_for @usergroup, html:  { class: "form-horizontal" } do |f|
  - if @usergroup.errors.any?
    div.alert.alert-danger.alert-dismissible
      button.close type="button" data-dismiss="alert" aria-label="Close"
        span aria-hidden="true" &times;
      - @usergroup.errors.full_messages.each do |message|
        = message
        br

  div.form-group
    = f.label :name, class: "col-sm-1 control-label"
    div.col-sm-4
      = f.text_field :name, class: "form-control", readonly: readonly
  div.form-group
    div.col-sm-offset-1.col-sm-4
      - if readonly == false
        = f.submit class: "btn btn-default"
      - links.each do |link|
        = link_to link[:title], link[:path], class: "btn btn-link"

app/views/usergroups/edit.html.slim
h1 Editing usergroup

== render 'form', :links => [ { :title => 'Show', :path => @usergroup }, { :title => 'Back', :path => usergroups_path } ]

app/views/usergroups/index.html.slim
h1
  'Usergroups
  = link_to new_usergroup_path
    span.glyphicon.glyphicon-plus

table.table.table-striped
  thead
    tr
      th Name
      th Action

  tbody
    - @usergroups.own(current_user).each do |usergroup|
      tr
        td = usergroup.name
        td
          = link_to usergroup do
            span.glyphicon.glyphicon-search
          '&nbsp;
          = link_to edit_usergroup_path(usergroup)
            span.glyphicon.glyphicon-pencil
          '&nbsp;
          = link_to usergroup, data: {:confirm => "Are you sure to delete usergroup '#{usergroup.name}'?"}, :method => :delete do
            span.glyphicon.glyphicon-remove

app/views/usergroups/new.html.slim
h1 New usergroup

== render 'form', :links => [ { :title => 'Back', :path => usergroups_path } ]

app/views/usergroups/show.html.slim
h1 Show usergroup

== render 'form', :links => [ { :title => 'Edit', :path => edit_usergroup_path(@usergroup) }, { :title => 'Back', :path => usergroups_path } ], :readonly => true

h1 Add user

= form_tag add_user_to_group_url, class: "form-horizontal" do
  div.form-group
    = label_tag :user_id, 'Add user', class: "col-sm-1 control-label"
    div.col-sm-4
      = select_tag "user_id", options_from_collection_for_select(User.where.not(id: current_user.id), 'id', 'email'), class: "form-control"
  div.form-group
    div.col-sm-offset-1.col-sm-4
      = submit_tag "Add user", class: "btn btn-default"

h1 Users in group

table.table.table-striped
  thead
    tr
      th User
      th Action

  tbody
    - @usergroup.users.each do |user|
      tr
        td = user.email
        td
          = link_to remove_user_from_group_url(@usergroup, user), data: {:confirm => "Are you sure to remove '#{user.email}'?"}, :method => :delete do
            span.glyphicon.glyphicon-remove