config/routes.rb
Rails.application.routes.draw do
  resources :notices
  resources :usergroups
  resources :categories
  devise_for :users

  root 'notices#index'

  post 'notice/access/:id' => 'notices#grant_access', as: :grant_notice_access
  delete 'notice/access/:id/:usergroup_id' => 'notices#revoke_access', as: :revoke_notice_access

  post 'usergroup/user/:id' => 'usergroups#add_user', as: :add_user_to_group
  delete 'usergroup/user/:id/:user_id' => 'usergroups#remove_user', as: :remove_user_from_group

end

app/models/notice.rb
class Notice < ActiveRecord::Base
  belongs_to :creator, :class_name => "User"
  belongs_to :category
  has_and_belongs_to_many :usergroups

  validates_presence_of :creator
  validates_presence_of :title
  validates_presence_of :category_id
  validates_presence_of :text

  scope :own, lambda { |user|
                           where("creator_id = ?", user.id)
                         }

  scope :accessgranted, lambda { |user|
                                    joins(:usergroups => :users).where("user_id = ?", user.id)
                                  }
end

app/controllers/notices_controller.rb
class NoticesController < ApplicationController
  before_action :set_notice, only: [:show, :edit, :update, :destroy, :grant_access, :revoke_access]
  before_action :set_usergroup, only: [:grant_access, :revoke_access]

  # GET /notices
  # GET /notices.json
  def index
    @notices = Notice.all
  end

  # GET /notices/1
  # GET /notices/1.json
  def show
    usergroups = @notice.usergroups
    found = false

    usergroups.each do |usergroup|
      unless usergroup.users.where(user_id: current_user.id).nil?
        found = true
      end
    end

    if @notice.creator == current_user || found

    else
      respond_to do |format|
        format.html { redirect_to notices_url, alert: 'You have no right to view this notice.' }
        format.json { head :no_content }
      end
    end
  end

  # GET /notices/new
  def new
    @notice = Notice.new
  end

  # GET /notices/1/edit
  def edit
    if @notice.creator == current_user

    else
      respond_to do |format|
        format.html { redirect_to notices_url, alert: 'You have no right to edit this notice.' }
        format.json { head :no_content }
      end
    end
  end

  # POST /notices
  # POST /notices.json
  def create
    @notice = Notice.new(notice_params)
    @notice.creator = current_user

    respond_to do |format|
      if @notice.save
        format.html { redirect_to @notice, notice: 'Notice was successfully created.' }
        format.json { render :show, status: :created, location: @notice }
      else
        format.html { render :new }
        format.json { render json: @notice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notices/1
  # PATCH/PUT /notices/1.json
  def update
    if @notice.creator == current_user
      respond_to do |format|
        if @notice.update(notice_params)
          format.html { redirect_to @notice, notice: 'Notice was successfully updated.' }
          format.json { render :show, status: :ok, location: @notice }
        else
          format.html { render :edit }
          format.json { render json: @notice.errors, status: :unprocessable_entity }
        end
      end
    else
      respond_to do |format|
        format.html { redirect_to notices_path, alert: 'You have no right to update this notice.' }
        format.json { head :no_content }
      end
    end
  end

  # DELETE /notices/1
  # DELETE /notices/1.json
  def destroy
    if @notice.creator == current_user
      @notice.destroy
      respond_to do |format|
        format.html { redirect_to notices_url, notice: 'Notice was successfully deleted.' }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html { redirect_to notices_url, alert: 'You have no right to delete this notice.' }
        format.json { head :no_content }
      end
    end
  end

  def grant_access
    if @notice.creator == current_user
      unless @usergroup.nil?
        begin
          @notice.usergroups.find(@usergroup)
        rescue ActiveRecord::RecordNotFound
          @notice.usergroups << @usergroup
        end

        respond_to do |format|
          format.html { redirect_to @notice, notice: 'Access granted.' }
          format.json { head :no_content }
        end
      else
        respond_to do |format|
          format.html { redirect_to @notice, notice: 'Usergroup not existent.' }
          format.json { head :no_content }
        end
      end
    else
      respond_to do |format|
        format.html { redirect_to @notice, alert: 'You have no right to grant access.' }
        format.json { head :no_content }
      end
    end
  end

  def revoke_access
    if @notice.creator == current_user
      unless @usergroup.nil?
        @notice.usergroups.delete(@usergroup)

        respond_to do |format|
          format.html { redirect_to @notice, notice: 'Access revoked.' }
          format.json { head :no_content }
        end
      else
        respond_to do |format|
          format.html { redirect_to @notice, notice: 'Usergroup not existent.' }
          format.json { head :no_content }
        end
      end
    else
      respond_to do |format|
        format.html { redirect_to @notice, alert: 'You have no right to revoke access.' }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_notice
      @notice = Notice.find(params[:id])
    end

    def set_usergroup
      @usergroup = Usergroup.where(id: params[:usergroup_id], admin: current_user)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def notice_params
      params.require(:notice).permit(:title, :category_id, :text)
    end
end

app/helpers/notices_helper.rb
module NoticesHelper
end

app/views/notices/_form.html.slim
- readonly ||= false

= form_for @notice, html:  { class: "form-horizontal" } do |f|
  - if @notice.errors.any?
    div.alert.alert-danger.alert-dismissible
      button.close type="button" data-dismiss="alert" aria-label="Close"
        span aria-hidden="true" &times;
      - @notice.errors.full_messages.each do |message|
        = message
        br

  - if readonly == true
    div.form-group
      = f.label :creator, class: "col-sm-1 control-label"
      div.col-sm-4
        = f.text_field :creator, class: "form-control", value: @notice.creator.email, readonly: readonly
  div.form-group
    = f.label :title, class: "col-sm-1 control-label"
    div.col-sm-4
      = f.text_field :title, class: "form-control", readonly: readonly
  div.form-group
    = f.label :category_id, class: "col-sm-1 control-label"
    div.col-sm-4
      - if readonly == true
        = f.text_field :category_id, class: "form-control", value: @notice.category.name, readonly: readonly
      - else
        = f.select :category_id, Category.all.pluck(:name, :id), class: "form-control", readonly: readonly
  div.form-group
    = f.label :text, class: "col-sm-1 control-label"
    div.col-sm-4
      = f.text_area :text, class: "form-control", readonly: readonly
  div.form-group
    div.col-sm-offset-1.col-sm-4
      - if readonly == false
        = f.submit class: "btn btn-default"
      - links.each do |link|
        = link_to link[:title], link[:path], class: "btn btn-link"

app/views/notices/edit.html.slim
h1 Editing notice

== render 'form', :links => [ { :title => 'Show', :path => @notice }, { :title => 'Back', :path => notices_path } ]

app/views/notices/index.html.slim
h1
  'Notices
  = link_to new_notice_path do
    span.glyphicon.glyphicon-plus

table#own_notices.table.table-striped
  thead
    tr
      th Title
      th Category
      th Action


  tbody
    - @notices.own(current_user).each do |notice|
      tr
        td = notice.title
        td = notice.category.name
        td
          = link_to notice do
            span.glyphicon.glyphicon-search
          '&nbsp;
          = link_to edit_notice_path(notice)
            span.glyphicon.glyphicon-pencil
          '&nbsp;
          = link_to notice, data: {:confirm => "Are you sure to delete notice '#{notice.title}'?"}, :method => :delete do
            span.glyphicon.glyphicon-remove

table#granted_notices.table.table-striped
  thead
    tr
      th Title
      th Category
      th Creator
      th Action

  tbody
    - @notices.accessgranted(current_user).each do |notice|
      tr
        td = notice.title
        td = notice.category.name
        td = notice.creator.email
        td
          = link_to notice do
            span.glyphicon.glyphicon-search

app/views/notices/new.html.slim
h1 New notice

== render 'form', :links => [ { :title => 'Back', :path => notices_path } ]

app/views/notices/show.html.slim
h1 Show notice

- if @notice.creator == current_user
  - links = [ { :title => 'Edit', :path => edit_notice_path(@notice) }, { :title => 'Back', :path => notices_path } ]
- else
  - links = [ { :title => 'Back', :path => notices_path } ]

== render 'form', :links => links, :readonly => true

- if @notice.creator == current_user
  h1 Grant access

  = form_tag grant_notice_access_url, class: "form-horizontal" do
    div.form-group
      = label_tag :usergroup_id, 'Grant to', class: "col-sm-1 control-label"
      div.col-sm-4
        = select_tag "usergroup_id", options_from_collection_for_select(Usergroup.where(admin_id: current_user.id), 'id', 'name'), class: "form-control"
    div.form-group
      div.col-sm-offset-1.col-sm-4
        = submit_tag "Grant access", class: "btn btn-default"

  h1 Access granted

  table.table.table-striped
    thead
      tr
        th Usergroup
        th Action

    tbody
      - @notice.usergroups.each do |usergroup|
        tr
          td = usergroup.name
          td
            = link_to revoke_notice_access_url(@notice, usergroup), data: {:confirm => "Are you sure to revoke the access for '#{usergroup.name}'?"}, :method => :delete do
              span.glyphicon.glyphicon-remove