config/routes.rb
Rails.application.routes.draw do
  resources :notices
  resources :usergroups
  resources :categories
  devise_for :users

  root 'notices#index'

  post 'notice/access/:id' => 'notices#grant_access', as: :grant_notice_access
  delete 'notice/access/:id/:usergroup_id' => 'notices#revoke_access', as: :revoke_notice_access

  post 'usergroup/user/:id' => 'usergroups#add_user', as: :add_user_to_group
  delete 'usergroup/user/:id/:user_id' => 'usergroups#remove_user', as: :remove_user_from_group

end

app/models/category.rb
class Category < ActiveRecord::Base
  validates_presence_of :name
  validates_uniqueness_of :name
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.slim
- readonly ||= false

= form_for @category, html:  { class: "form-horizontal" } do |f|
  - if @category.errors.any?
    div.alert.alert-danger.alert-dismissible
      button.close type="button" data-dismiss="alert" aria-label="Close"
        span aria-hidden="true" &times;
      - @category.errors.full_messages.each do |message|
        = message

  div.form-group
    = f.label :name, class: "col-sm-1 control-label"
    div.col-sm-4
      = f.text_field :name, class: "form-control", readonly: readonly
  div.form-group
    div.col-sm-offset-1.col-sm-4
      - if readonly == false
        = f.submit class: "btn btn-default"
      - links.each do |link|
        = link_to link[:title], link[:path], class: "btn btn-link"

app/views/categories/edit.html.slim
h1 Editing category

== render 'form', :links => [ { :title => 'Show', :path => @category }, { :title => 'Back', :path => categories_path } ]

app/views/categories/index.html.slim
h1
  'Categories
  = link_to new_category_path do
    span.glyphicon.glyphicon-plus

table.table.table-striped
  thead
    tr
      th Name
      th Action

  tbody
    - @categories.each do |category|
      tr
        td = category.name
        td
          = link_to category do
            span.glyphicon.glyphicon-search
          '&nbsp;
          = link_to edit_category_path(category)
            span.glyphicon.glyphicon-pencil
          '&nbsp;
          = link_to category, data: {:confirm => "Are you sure to delete category '#{category.name}'?"}, :method => :delete do
            span.glyphicon.glyphicon-remove

app/views/categories/new.html.slim
h1 New category

== render 'form', :links => [ { :title => 'Back', :path => categories_path } ]

app/views/categories/show.html.slim
h1 Show category

== render 'form', :links => [ { :title => 'Edit', :path => edit_category_path(@category) }, { :title => 'Back', :path => categories_path } ], :readonly => true