config/routes.rb
Rails.application.routes.draw do
  resources :notices
  resources :usergroups
  resources :categories
  devise_for :users

  root 'notices#index'

  post 'notice/access/:id' => 'notices#grant_access', as: :grant_notice_access
  delete 'notice/access/:id/:usergroup_id' => 'notices#revoke_access', as: :revoke_notice_access

  post 'usergroup/user/:id' => 'usergroups#add_user', as: :add_user_to_group
  delete 'usergroup/user/:id/:user_id' => 'usergroups#remove_user', as: :remove_user_from_group

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>NoticeBoard</title>
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
        <%= csrf_meta_tags %>
    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-static-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="#">NoticeBoard</a>
                </div>
                <div class="collapse navbar-collapse" id="navbar">
                    <ul class="nav navbar-nav navbar-left">
                        <% if user_signed_in? %>
                            <li><%= link_to 'Notices', notices_path, :class => 'navbar-link' %></li>
                            <li><%= link_to 'Usergroups', usergroups_path, :class => 'navbar-link' %></li>
                            <li><%= link_to 'Categories', categories_path, :class => 'navbar-link' %></li>
                        <% end %>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <% if user_signed_in? %>
                            <li><p class="navbar-text">Logged in as <strong><%= current_user.email %></strong>.</p></li>
                            <li><%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %></li>
                            <li><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></li>
                        <% else %>
                            <li><%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %></li>
                            <li><%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %></li>
                        <% end %>
                    </ul>
                </div>
            </div>
        </nav>
        <div class="container">
            <% if notice %>
                <div id="notice" class="alert alert-success alert-dismissible">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <%= notice %>
                </div>
            <% end %>
            <% if alert %>
                <div id="alert" class="alert alert-danger alert-dismissible">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <%= alert %>
                </div>
            <% end %>
            <%= yield %>
        </div>
    </body>
</html>